language: node_js
node_js:
  - v10
  - v8
  - v6
cache:
  directories:
    - "node_modules"
before_install:
  - npm i npm@^6 -g
install:
  - npm install
script:
  - npm test
notifications:
  email: false
